//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication008.WCFServicioDatos {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeDetails", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class EmployeeDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EmpIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> SalaryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorkTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmpId {
            get {
                return this.EmpIdField;
            }
            set {
                if ((this.EmpIdField.Equals(value) != true)) {
                    this.EmpIdField = value;
                    this.RaisePropertyChanged("EmpId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Salary {
            get {
                return this.SalaryField;
            }
            set {
                if ((this.SalaryField.Equals(value) != true)) {
                    this.SalaryField = value;
                    this.RaisePropertyChanged("Salary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkType {
            get {
                return this.WorkTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkTypeField, value) != true)) {
                    this.WorkTypeField = value;
                    this.RaisePropertyChanged("WorkType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido {
            get {
                return this.ApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoField, value) != true)) {
                    this.ApellidoField = value;
                    this.RaisePropertyChanged("Apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuarios", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class Usuarios : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string claveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_usuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string loginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rolField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apellido {
            get {
                return this.apellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.apellidoField, value) != true)) {
                    this.apellidoField = value;
                    this.RaisePropertyChanged("apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string clave {
            get {
                return this.claveField;
            }
            set {
                if ((object.ReferenceEquals(this.claveField, value) != true)) {
                    this.claveField = value;
                    this.RaisePropertyChanged("clave");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_usuario {
            get {
                return this.id_usuarioField;
            }
            set {
                if ((this.id_usuarioField.Equals(value) != true)) {
                    this.id_usuarioField = value;
                    this.RaisePropertyChanged("id_usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string login {
            get {
                return this.loginField;
            }
            set {
                if ((object.ReferenceEquals(this.loginField, value) != true)) {
                    this.loginField = value;
                    this.RaisePropertyChanged("login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rol {
            get {
                return this.rolField;
            }
            set {
                if ((object.ReferenceEquals(this.rolField, value) != true)) {
                    this.rolField = value;
                    this.RaisePropertyChanged("rol");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Trabajos", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class Trabajos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string archivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> fecha_entregaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> id_materiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_trabajoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> id_usuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tipo_trabajoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string archivo {
            get {
                return this.archivoField;
            }
            set {
                if ((object.ReferenceEquals(this.archivoField, value) != true)) {
                    this.archivoField = value;
                    this.RaisePropertyChanged("archivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> fecha_entrega {
            get {
                return this.fecha_entregaField;
            }
            set {
                if ((this.fecha_entregaField.Equals(value) != true)) {
                    this.fecha_entregaField = value;
                    this.RaisePropertyChanged("fecha_entrega");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> id_materia {
            get {
                return this.id_materiaField;
            }
            set {
                if ((this.id_materiaField.Equals(value) != true)) {
                    this.id_materiaField = value;
                    this.RaisePropertyChanged("id_materia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_trabajo {
            get {
                return this.id_trabajoField;
            }
            set {
                if ((this.id_trabajoField.Equals(value) != true)) {
                    this.id_trabajoField = value;
                    this.RaisePropertyChanged("id_trabajo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> id_usuario {
            get {
                return this.id_usuarioField;
            }
            set {
                if ((this.id_usuarioField.Equals(value) != true)) {
                    this.id_usuarioField = value;
                    this.RaisePropertyChanged("id_usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tipo_trabajo {
            get {
                return this.tipo_trabajoField;
            }
            set {
                if ((object.ReferenceEquals(this.tipo_trabajoField, value) != true)) {
                    this.tipo_trabajoField = value;
                    this.RaisePropertyChanged("tipo_trabajo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Materias", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class Materias : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_materiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoField, value) != true)) {
                    this.codigoField = value;
                    this.RaisePropertyChanged("codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionField, value) != true)) {
                    this.descripcionField = value;
                    this.RaisePropertyChanged("descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_materia {
            get {
                return this.id_materiaField;
            }
            set {
                if ((this.id_materiaField.Equals(value) != true)) {
                    this.id_materiaField = value;
                    this.RaisePropertyChanged("id_materia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFServicioDatos.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/InsertarEmpleado", ReplyAction="http://tempuri.org/IService/InsertarEmpleadoResponse")]
        int InsertarEmpleado(WebApplication008.WCFServicioDatos.EmployeeDetails empleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/InsertarEmpleado", ReplyAction="http://tempuri.org/IService/InsertarEmpleadoResponse")]
        System.Threading.Tasks.Task<int> InsertarEmpleadoAsync(WebApplication008.WCFServicioDatos.EmployeeDetails empleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ListarTodosEmpleados", ReplyAction="http://tempuri.org/IService/ListarTodosEmpleadosResponse")]
        WebApplication008.WCFServicioDatos.EmployeeDetails[] ListarTodosEmpleados();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ListarTodosEmpleados", ReplyAction="http://tempuri.org/IService/ListarTodosEmpleadosResponse")]
        System.Threading.Tasks.Task<WebApplication008.WCFServicioDatos.EmployeeDetails[]> ListarTodosEmpleadosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ObtenerEmpleadoPorId", ReplyAction="http://tempuri.org/IService/ObtenerEmpleadoPorIdResponse")]
        WebApplication008.WCFServicioDatos.EmployeeDetails ObtenerEmpleadoPorId(int empId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ObtenerEmpleadoPorId", ReplyAction="http://tempuri.org/IService/ObtenerEmpleadoPorIdResponse")]
        System.Threading.Tasks.Task<WebApplication008.WCFServicioDatos.EmployeeDetails> ObtenerEmpleadoPorIdAsync(int empId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ObtenerEmpleadosPorNombre", ReplyAction="http://tempuri.org/IService/ObtenerEmpleadosPorNombreResponse")]
        WebApplication008.WCFServicioDatos.EmployeeDetails[] ObtenerEmpleadosPorNombre(string Name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ObtenerEmpleadosPorNombre", ReplyAction="http://tempuri.org/IService/ObtenerEmpleadosPorNombreResponse")]
        System.Threading.Tasks.Task<WebApplication008.WCFServicioDatos.EmployeeDetails[]> ObtenerEmpleadosPorNombreAsync(string Name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ModificarEmpleado", ReplyAction="http://tempuri.org/IService/ModificarEmpleadoResponse")]
        int ModificarEmpleado(WebApplication008.WCFServicioDatos.EmployeeDetails emp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ModificarEmpleado", ReplyAction="http://tempuri.org/IService/ModificarEmpleadoResponse")]
        System.Threading.Tasks.Task<int> ModificarEmpleadoAsync(WebApplication008.WCFServicioDatos.EmployeeDetails emp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/BorrarEmpleadoPorId", ReplyAction="http://tempuri.org/IService/BorrarEmpleadoPorIdResponse")]
        int BorrarEmpleadoPorId(int empId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/BorrarEmpleadoPorId", ReplyAction="http://tempuri.org/IService/BorrarEmpleadoPorIdResponse")]
        System.Threading.Tasks.Task<int> BorrarEmpleadoPorIdAsync(int empId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/InsertarUsuario", ReplyAction="http://tempuri.org/IService/InsertarUsuarioResponse")]
        int InsertarUsuario(WebApplication008.WCFServicioDatos.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/InsertarUsuario", ReplyAction="http://tempuri.org/IService/InsertarUsuarioResponse")]
        System.Threading.Tasks.Task<int> InsertarUsuarioAsync(WebApplication008.WCFServicioDatos.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ListarTodosUsuarios", ReplyAction="http://tempuri.org/IService/ListarTodosUsuariosResponse")]
        WebApplication008.WCFServicioDatos.Usuario[] ListarTodosUsuarios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ListarTodosUsuarios", ReplyAction="http://tempuri.org/IService/ListarTodosUsuariosResponse")]
        System.Threading.Tasks.Task<WebApplication008.WCFServicioDatos.Usuario[]> ListarTodosUsuariosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ObtenerUsuarioPorId", ReplyAction="http://tempuri.org/IService/ObtenerUsuarioPorIdResponse")]
        WebApplication008.WCFServicioDatos.Usuario ObtenerUsuarioPorId(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ObtenerUsuarioPorId", ReplyAction="http://tempuri.org/IService/ObtenerUsuarioPorIdResponse")]
        System.Threading.Tasks.Task<WebApplication008.WCFServicioDatos.Usuario> ObtenerUsuarioPorIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ObtenerUsuariosPorNombre", ReplyAction="http://tempuri.org/IService/ObtenerUsuariosPorNombreResponse")]
        WebApplication008.WCFServicioDatos.Usuario[] ObtenerUsuariosPorNombre(string Name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ObtenerUsuariosPorNombre", ReplyAction="http://tempuri.org/IService/ObtenerUsuariosPorNombreResponse")]
        System.Threading.Tasks.Task<WebApplication008.WCFServicioDatos.Usuario[]> ObtenerUsuariosPorNombreAsync(string Name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ModificarUsuario", ReplyAction="http://tempuri.org/IService/ModificarUsuarioResponse")]
        int ModificarUsuario(WebApplication008.WCFServicioDatos.Usuario user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ModificarUsuario", ReplyAction="http://tempuri.org/IService/ModificarUsuarioResponse")]
        System.Threading.Tasks.Task<int> ModificarUsuarioAsync(WebApplication008.WCFServicioDatos.Usuario user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/BorrarUsuarioPorId", ReplyAction="http://tempuri.org/IService/BorrarUsuarioPorIdResponse")]
        int BorrarUsuarioPorId(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/BorrarUsuarioPorId", ReplyAction="http://tempuri.org/IService/BorrarUsuarioPorIdResponse")]
        System.Threading.Tasks.Task<int> BorrarUsuarioPorIdAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CrearUsuario", ReplyAction="http://tempuri.org/IService/CrearUsuarioResponse")]
        bool CrearUsuario(WebApplication008.WCFServicioDatos.Usuarios usuarios);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CrearUsuario", ReplyAction="http://tempuri.org/IService/CrearUsuarioResponse")]
        System.Threading.Tasks.Task<bool> CrearUsuarioAsync(WebApplication008.WCFServicioDatos.Usuarios usuarios);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ConsultarUsuarios", ReplyAction="http://tempuri.org/IService/ConsultarUsuariosResponse")]
        WebApplication008.WCFServicioDatos.Usuarios[] ConsultarUsuarios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ConsultarUsuarios", ReplyAction="http://tempuri.org/IService/ConsultarUsuariosResponse")]
        System.Threading.Tasks.Task<WebApplication008.WCFServicioDatos.Usuarios[]> ConsultarUsuariosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ConsultarUsuarioPorId", ReplyAction="http://tempuri.org/IService/ConsultarUsuarioPorIdResponse")]
        WebApplication008.WCFServicioDatos.Usuarios ConsultarUsuarioPorId(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ConsultarUsuarioPorId", ReplyAction="http://tempuri.org/IService/ConsultarUsuarioPorIdResponse")]
        System.Threading.Tasks.Task<WebApplication008.WCFServicioDatos.Usuarios> ConsultarUsuarioPorIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ConsultarUsuariosPorNombre", ReplyAction="http://tempuri.org/IService/ConsultarUsuariosPorNombreResponse")]
        WebApplication008.WCFServicioDatos.Usuarios[] ConsultarUsuariosPorNombre(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ConsultarUsuariosPorNombre", ReplyAction="http://tempuri.org/IService/ConsultarUsuariosPorNombreResponse")]
        System.Threading.Tasks.Task<WebApplication008.WCFServicioDatos.Usuarios[]> ConsultarUsuariosPorNombreAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ConsultarUsuariosPorLogin", ReplyAction="http://tempuri.org/IService/ConsultarUsuariosPorLoginResponse")]
        WebApplication008.WCFServicioDatos.Usuarios[] ConsultarUsuariosPorLogin(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ConsultarUsuariosPorLogin", ReplyAction="http://tempuri.org/IService/ConsultarUsuariosPorLoginResponse")]
        System.Threading.Tasks.Task<WebApplication008.WCFServicioDatos.Usuarios[]> ConsultarUsuariosPorLoginAsync(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditarUsuario", ReplyAction="http://tempuri.org/IService/EditarUsuarioResponse")]
        bool EditarUsuario(WebApplication008.WCFServicioDatos.Usuarios users);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditarUsuario", ReplyAction="http://tempuri.org/IService/EditarUsuarioResponse")]
        System.Threading.Tasks.Task<bool> EditarUsuarioAsync(WebApplication008.WCFServicioDatos.Usuarios users);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EliminarUsuarioPorId", ReplyAction="http://tempuri.org/IService/EliminarUsuarioPorIdResponse")]
        bool EliminarUsuarioPorId(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EliminarUsuarioPorId", ReplyAction="http://tempuri.org/IService/EliminarUsuarioPorIdResponse")]
        System.Threading.Tasks.Task<bool> EliminarUsuarioPorIdAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CrearTrabajo", ReplyAction="http://tempuri.org/IService/CrearTrabajoResponse")]
        bool CrearTrabajo(WebApplication008.WCFServicioDatos.Trabajos trabajo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CrearTrabajo", ReplyAction="http://tempuri.org/IService/CrearTrabajoResponse")]
        System.Threading.Tasks.Task<bool> CrearTrabajoAsync(WebApplication008.WCFServicioDatos.Trabajos trabajo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditarTrabajo", ReplyAction="http://tempuri.org/IService/EditarTrabajoResponse")]
        bool EditarTrabajo(WebApplication008.WCFServicioDatos.Trabajos trabajo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditarTrabajo", ReplyAction="http://tempuri.org/IService/EditarTrabajoResponse")]
        System.Threading.Tasks.Task<bool> EditarTrabajoAsync(WebApplication008.WCFServicioDatos.Trabajos trabajo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ListarTrabajosPorIdMateria", ReplyAction="http://tempuri.org/IService/ListarTrabajosPorIdMateriaResponse")]
        WebApplication008.WCFServicioDatos.Trabajos[] ListarTrabajosPorIdMateria(int id_materia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ListarTrabajosPorIdMateria", ReplyAction="http://tempuri.org/IService/ListarTrabajosPorIdMateriaResponse")]
        System.Threading.Tasks.Task<WebApplication008.WCFServicioDatos.Trabajos[]> ListarTrabajosPorIdMateriaAsync(int id_materia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ListarTrabajosPorIdMateriaPorUsuario", ReplyAction="http://tempuri.org/IService/ListarTrabajosPorIdMateriaPorUsuarioResponse")]
        WebApplication008.WCFServicioDatos.Trabajos[] ListarTrabajosPorIdMateriaPorUsuario(int id_materia, int id_usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ListarTrabajosPorIdMateriaPorUsuario", ReplyAction="http://tempuri.org/IService/ListarTrabajosPorIdMateriaPorUsuarioResponse")]
        System.Threading.Tasks.Task<WebApplication008.WCFServicioDatos.Trabajos[]> ListarTrabajosPorIdMateriaPorUsuarioAsync(int id_materia, int id_usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EliminarTrabajoPorId", ReplyAction="http://tempuri.org/IService/EliminarTrabajoPorIdResponse")]
        bool EliminarTrabajoPorId(int idTrabajo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EliminarTrabajoPorId", ReplyAction="http://tempuri.org/IService/EliminarTrabajoPorIdResponse")]
        System.Threading.Tasks.Task<bool> EliminarTrabajoPorIdAsync(int idTrabajo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CrearMateria", ReplyAction="http://tempuri.org/IService/CrearMateriaResponse")]
        bool CrearMateria(WebApplication008.WCFServicioDatos.Materias materia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CrearMateria", ReplyAction="http://tempuri.org/IService/CrearMateriaResponse")]
        System.Threading.Tasks.Task<bool> CrearMateriaAsync(WebApplication008.WCFServicioDatos.Materias materia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditarMateria", ReplyAction="http://tempuri.org/IService/EditarMateriaResponse")]
        bool EditarMateria(WebApplication008.WCFServicioDatos.Materias materia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditarMateria", ReplyAction="http://tempuri.org/IService/EditarMateriaResponse")]
        System.Threading.Tasks.Task<bool> EditarMateriaAsync(WebApplication008.WCFServicioDatos.Materias materia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ListarMaterias", ReplyAction="http://tempuri.org/IService/ListarMateriasResponse")]
        WebApplication008.WCFServicioDatos.Materias[] ListarMaterias();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ListarMaterias", ReplyAction="http://tempuri.org/IService/ListarMateriasResponse")]
        System.Threading.Tasks.Task<WebApplication008.WCFServicioDatos.Materias[]> ListarMateriasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ListarMateriasPorId", ReplyAction="http://tempuri.org/IService/ListarMateriasPorIdResponse")]
        WebApplication008.WCFServicioDatos.Materias[] ListarMateriasPorId(int idMateria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ListarMateriasPorId", ReplyAction="http://tempuri.org/IService/ListarMateriasPorIdResponse")]
        System.Threading.Tasks.Task<WebApplication008.WCFServicioDatos.Materias[]> ListarMateriasPorIdAsync(int idMateria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EliminarMateriaPorId", ReplyAction="http://tempuri.org/IService/EliminarMateriaPorIdResponse")]
        bool EliminarMateriaPorId(int idMateria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EliminarMateriaPorId", ReplyAction="http://tempuri.org/IService/EliminarMateriaPorIdResponse")]
        System.Threading.Tasks.Task<bool> EliminarMateriaPorIdAsync(int idMateria);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : WebApplication008.WCFServicioDatos.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<WebApplication008.WCFServicioDatos.IService>, WebApplication008.WCFServicioDatos.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int InsertarEmpleado(WebApplication008.WCFServicioDatos.EmployeeDetails empleado) {
            return base.Channel.InsertarEmpleado(empleado);
        }
        
        public System.Threading.Tasks.Task<int> InsertarEmpleadoAsync(WebApplication008.WCFServicioDatos.EmployeeDetails empleado) {
            return base.Channel.InsertarEmpleadoAsync(empleado);
        }
        
        public WebApplication008.WCFServicioDatos.EmployeeDetails[] ListarTodosEmpleados() {
            return base.Channel.ListarTodosEmpleados();
        }
        
        public System.Threading.Tasks.Task<WebApplication008.WCFServicioDatos.EmployeeDetails[]> ListarTodosEmpleadosAsync() {
            return base.Channel.ListarTodosEmpleadosAsync();
        }
        
        public WebApplication008.WCFServicioDatos.EmployeeDetails ObtenerEmpleadoPorId(int empId) {
            return base.Channel.ObtenerEmpleadoPorId(empId);
        }
        
        public System.Threading.Tasks.Task<WebApplication008.WCFServicioDatos.EmployeeDetails> ObtenerEmpleadoPorIdAsync(int empId) {
            return base.Channel.ObtenerEmpleadoPorIdAsync(empId);
        }
        
        public WebApplication008.WCFServicioDatos.EmployeeDetails[] ObtenerEmpleadosPorNombre(string Name) {
            return base.Channel.ObtenerEmpleadosPorNombre(Name);
        }
        
        public System.Threading.Tasks.Task<WebApplication008.WCFServicioDatos.EmployeeDetails[]> ObtenerEmpleadosPorNombreAsync(string Name) {
            return base.Channel.ObtenerEmpleadosPorNombreAsync(Name);
        }
        
        public int ModificarEmpleado(WebApplication008.WCFServicioDatos.EmployeeDetails emp) {
            return base.Channel.ModificarEmpleado(emp);
        }
        
        public System.Threading.Tasks.Task<int> ModificarEmpleadoAsync(WebApplication008.WCFServicioDatos.EmployeeDetails emp) {
            return base.Channel.ModificarEmpleadoAsync(emp);
        }
        
        public int BorrarEmpleadoPorId(int empId) {
            return base.Channel.BorrarEmpleadoPorId(empId);
        }
        
        public System.Threading.Tasks.Task<int> BorrarEmpleadoPorIdAsync(int empId) {
            return base.Channel.BorrarEmpleadoPorIdAsync(empId);
        }
        
        public int InsertarUsuario(WebApplication008.WCFServicioDatos.Usuario usuario) {
            return base.Channel.InsertarUsuario(usuario);
        }
        
        public System.Threading.Tasks.Task<int> InsertarUsuarioAsync(WebApplication008.WCFServicioDatos.Usuario usuario) {
            return base.Channel.InsertarUsuarioAsync(usuario);
        }
        
        public WebApplication008.WCFServicioDatos.Usuario[] ListarTodosUsuarios() {
            return base.Channel.ListarTodosUsuarios();
        }
        
        public System.Threading.Tasks.Task<WebApplication008.WCFServicioDatos.Usuario[]> ListarTodosUsuariosAsync() {
            return base.Channel.ListarTodosUsuariosAsync();
        }
        
        public WebApplication008.WCFServicioDatos.Usuario ObtenerUsuarioPorId(int id) {
            return base.Channel.ObtenerUsuarioPorId(id);
        }
        
        public System.Threading.Tasks.Task<WebApplication008.WCFServicioDatos.Usuario> ObtenerUsuarioPorIdAsync(int id) {
            return base.Channel.ObtenerUsuarioPorIdAsync(id);
        }
        
        public WebApplication008.WCFServicioDatos.Usuario[] ObtenerUsuariosPorNombre(string Name) {
            return base.Channel.ObtenerUsuariosPorNombre(Name);
        }
        
        public System.Threading.Tasks.Task<WebApplication008.WCFServicioDatos.Usuario[]> ObtenerUsuariosPorNombreAsync(string Name) {
            return base.Channel.ObtenerUsuariosPorNombreAsync(Name);
        }
        
        public int ModificarUsuario(WebApplication008.WCFServicioDatos.Usuario user) {
            return base.Channel.ModificarUsuario(user);
        }
        
        public System.Threading.Tasks.Task<int> ModificarUsuarioAsync(WebApplication008.WCFServicioDatos.Usuario user) {
            return base.Channel.ModificarUsuarioAsync(user);
        }
        
        public int BorrarUsuarioPorId(int Id) {
            return base.Channel.BorrarUsuarioPorId(Id);
        }
        
        public System.Threading.Tasks.Task<int> BorrarUsuarioPorIdAsync(int Id) {
            return base.Channel.BorrarUsuarioPorIdAsync(Id);
        }
        
        public bool CrearUsuario(WebApplication008.WCFServicioDatos.Usuarios usuarios) {
            return base.Channel.CrearUsuario(usuarios);
        }
        
        public System.Threading.Tasks.Task<bool> CrearUsuarioAsync(WebApplication008.WCFServicioDatos.Usuarios usuarios) {
            return base.Channel.CrearUsuarioAsync(usuarios);
        }
        
        public WebApplication008.WCFServicioDatos.Usuarios[] ConsultarUsuarios() {
            return base.Channel.ConsultarUsuarios();
        }
        
        public System.Threading.Tasks.Task<WebApplication008.WCFServicioDatos.Usuarios[]> ConsultarUsuariosAsync() {
            return base.Channel.ConsultarUsuariosAsync();
        }
        
        public WebApplication008.WCFServicioDatos.Usuarios ConsultarUsuarioPorId(int id) {
            return base.Channel.ConsultarUsuarioPorId(id);
        }
        
        public System.Threading.Tasks.Task<WebApplication008.WCFServicioDatos.Usuarios> ConsultarUsuarioPorIdAsync(int id) {
            return base.Channel.ConsultarUsuarioPorIdAsync(id);
        }
        
        public WebApplication008.WCFServicioDatos.Usuarios[] ConsultarUsuariosPorNombre(string name) {
            return base.Channel.ConsultarUsuariosPorNombre(name);
        }
        
        public System.Threading.Tasks.Task<WebApplication008.WCFServicioDatos.Usuarios[]> ConsultarUsuariosPorNombreAsync(string name) {
            return base.Channel.ConsultarUsuariosPorNombreAsync(name);
        }
        
        public WebApplication008.WCFServicioDatos.Usuarios[] ConsultarUsuariosPorLogin(string login) {
            return base.Channel.ConsultarUsuariosPorLogin(login);
        }
        
        public System.Threading.Tasks.Task<WebApplication008.WCFServicioDatos.Usuarios[]> ConsultarUsuariosPorLoginAsync(string login) {
            return base.Channel.ConsultarUsuariosPorLoginAsync(login);
        }
        
        public bool EditarUsuario(WebApplication008.WCFServicioDatos.Usuarios users) {
            return base.Channel.EditarUsuario(users);
        }
        
        public System.Threading.Tasks.Task<bool> EditarUsuarioAsync(WebApplication008.WCFServicioDatos.Usuarios users) {
            return base.Channel.EditarUsuarioAsync(users);
        }
        
        public bool EliminarUsuarioPorId(int userId) {
            return base.Channel.EliminarUsuarioPorId(userId);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarUsuarioPorIdAsync(int userId) {
            return base.Channel.EliminarUsuarioPorIdAsync(userId);
        }
        
        public bool CrearTrabajo(WebApplication008.WCFServicioDatos.Trabajos trabajo) {
            return base.Channel.CrearTrabajo(trabajo);
        }
        
        public System.Threading.Tasks.Task<bool> CrearTrabajoAsync(WebApplication008.WCFServicioDatos.Trabajos trabajo) {
            return base.Channel.CrearTrabajoAsync(trabajo);
        }
        
        public bool EditarTrabajo(WebApplication008.WCFServicioDatos.Trabajos trabajo) {
            return base.Channel.EditarTrabajo(trabajo);
        }
        
        public System.Threading.Tasks.Task<bool> EditarTrabajoAsync(WebApplication008.WCFServicioDatos.Trabajos trabajo) {
            return base.Channel.EditarTrabajoAsync(trabajo);
        }
        
        public WebApplication008.WCFServicioDatos.Trabajos[] ListarTrabajosPorIdMateria(int id_materia) {
            return base.Channel.ListarTrabajosPorIdMateria(id_materia);
        }
        
        public System.Threading.Tasks.Task<WebApplication008.WCFServicioDatos.Trabajos[]> ListarTrabajosPorIdMateriaAsync(int id_materia) {
            return base.Channel.ListarTrabajosPorIdMateriaAsync(id_materia);
        }
        
        public WebApplication008.WCFServicioDatos.Trabajos[] ListarTrabajosPorIdMateriaPorUsuario(int id_materia, int id_usuario) {
            return base.Channel.ListarTrabajosPorIdMateriaPorUsuario(id_materia, id_usuario);
        }
        
        public System.Threading.Tasks.Task<WebApplication008.WCFServicioDatos.Trabajos[]> ListarTrabajosPorIdMateriaPorUsuarioAsync(int id_materia, int id_usuario) {
            return base.Channel.ListarTrabajosPorIdMateriaPorUsuarioAsync(id_materia, id_usuario);
        }
        
        public bool EliminarTrabajoPorId(int idTrabajo) {
            return base.Channel.EliminarTrabajoPorId(idTrabajo);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarTrabajoPorIdAsync(int idTrabajo) {
            return base.Channel.EliminarTrabajoPorIdAsync(idTrabajo);
        }
        
        public bool CrearMateria(WebApplication008.WCFServicioDatos.Materias materia) {
            return base.Channel.CrearMateria(materia);
        }
        
        public System.Threading.Tasks.Task<bool> CrearMateriaAsync(WebApplication008.WCFServicioDatos.Materias materia) {
            return base.Channel.CrearMateriaAsync(materia);
        }
        
        public bool EditarMateria(WebApplication008.WCFServicioDatos.Materias materia) {
            return base.Channel.EditarMateria(materia);
        }
        
        public System.Threading.Tasks.Task<bool> EditarMateriaAsync(WebApplication008.WCFServicioDatos.Materias materia) {
            return base.Channel.EditarMateriaAsync(materia);
        }
        
        public WebApplication008.WCFServicioDatos.Materias[] ListarMaterias() {
            return base.Channel.ListarMaterias();
        }
        
        public System.Threading.Tasks.Task<WebApplication008.WCFServicioDatos.Materias[]> ListarMateriasAsync() {
            return base.Channel.ListarMateriasAsync();
        }
        
        public WebApplication008.WCFServicioDatos.Materias[] ListarMateriasPorId(int idMateria) {
            return base.Channel.ListarMateriasPorId(idMateria);
        }
        
        public System.Threading.Tasks.Task<WebApplication008.WCFServicioDatos.Materias[]> ListarMateriasPorIdAsync(int idMateria) {
            return base.Channel.ListarMateriasPorIdAsync(idMateria);
        }
        
        public bool EliminarMateriaPorId(int idMateria) {
            return base.Channel.EliminarMateriaPorId(idMateria);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarMateriaPorIdAsync(int idMateria) {
            return base.Channel.EliminarMateriaPorIdAsync(idMateria);
        }
    }
}
